version: "3"
services:
  webhook:
    container_name: webhook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment: 
      - GITHUB_WEBHOOK_SECRET=test_github_webhook
      - GITHUB_REPO_BRANCH=master
      - LOCAL_REPO_DIR=/code
      - PORT=3000
